### ISSUE TITLE
analysis error with figwheel >= 5.5

### ISSUE THREAD

**Issue by pkpkpk** [mfikes/andare#2]
Using either andare `0.1.0` or `0.2.0` fails when using figwheel `0.5.5` or later on cljs `1.9.229`

```
----  Could not Analyze  target/out/cljs/core/async.cljs  ----
java.lang.RuntimeException: No such var: ioc/state-machine, compiling:(cljs/core/async/macros.clj:18:19)
```

which refers to:
https://github.com/mfikes/andare/commit/9419fa02f49c293f90da80bb62134e5f2aed94ea#diff-283073ca0e5bfffccdd5ce09cbcc002aL18

Presumably this is figwheel compiling andare .cljs using macros_.clj_ from its own core.async dep rather than macros_.cljc_ from andare

I saw this problem previously when you pushed `0.2.0`, so I stuck with `0.1.0` which worked fine with figwheel `0.5.4-7` (whereas andare `0.2.0` raises above error). But now with latest figwheel, neither release works. I imagine excluding core async from fw would solve the problem but unfortunately leiningen plugin exclusions are currently broken

**Comment by mfikes** [comment]
Right. Andare is designed to use the same (public API) namespaces as `core.async` so that it can be used as a drop-in replacement for self-host use. Having the both Andare and the official `core.async` JAR on the classpath could easily cause problems like this.

**Comment by pkpkpk** [comment]
Yes this has nothing to do with Andare, my apologies.  Thanks again for all your working on this.
