### ISSUE TITLE
Quick-start documentation

### ISSUE THREAD

**Issue by chr15m** [mfikes/andare#3]
I am having trouble figuring out how to use this module with `lumo`. I've tried searching for "lumo simple andare example" which does not yield much. I have `lumo` installed via npm and I can successfully run `.cljs` scripts by doing `lumo myscript.cljs` and import node modules from `node_modules` which have been installed with `npm`.

What steps do I need to take to integrate andare into this setup?

**Comment by chr15m** [comment]
For future passers by I was able to get this working as follows:

 * Create a minimal `project.clj` file with these contents:

```
(defproject YOUR-PROJECT-NAME "0.0.1-SNAPSHOT"
  :dependencies [[andare "0.7.0"]])
```

 * Ask lein to install the dependency into the local maven repository:

`lein classpath`

 * Launch lumo with the `-D` flag to tell it to use andare:

`./node_modules/.bin/lumo -D andare:0.7.0 YOUR-SCRIPT.cljs`

You can also use the lein classpath like this:

`./node_modules/.bin/lumo -c `lein classpath` YOUR-SCRIPT.cljs `

Thanks @mfikes! Not sure if this needs to go into andare documentation or lumo documentation or if it's general knowledge. :thinking:

**Comment by mfikes** [comment]
@chr15m Well, Andare is a library just like any other. Environment-specific details on how libraries are consumed belongs with the environment-specific documentation, IMHO.

While Andare works with Lumo, Andare was not built specifically for Lumo (it predates Lumo by about half a year). It is usable in any codebase making use of self-hosted ClojureScript.

**Comment by chr15m** [comment]
@mfikes true this is probably something that should be documented in lumo. Thanks!
